setup.py
This *might* make the description render more nicely on PyPI.
=> setup.py: Remove extra space

docs/sources/user_guide/file_io/find_files.ipynb
- [/] Create and check out a new topic branch
- [/] Implement the new feature or apply the bug-fix
- [N/A] Add appropriate unit test functions in the `./mlxtend/*/tests` directories
- [N/A] Run `nosetests ./mlxtend -sv` and make sure that all unit tests pass
- [N/A] Check/improve the test coverage by running `nosetests ./mlxtend --with-coverage`
- [N/A] Check for style issues by running `flake8 ./mlxtend` (you may want to run nosetests again after you made modifications to the code)
- [N/A] Add a note about the modification or contribution to the `./docs/sources/`CHANGELOG.md` file
- [/] Modify documentation in the appropriate location under `mlxtend/docs/sources/`
- [/] Push the topic branch to the server and create a pull request
- [/] Check the Travis-CI build passed at …
=> Fix minor typo in find_files documentation

docs/sources/CHANGELOG.md, mlxtend/classifier/stacking_classification.py, mlxtend/classifier/tests/test_stacking_classifier.py
=> Stacking probas

mlxtend/evaluate/decision_regions.py, mlxtend/evaluate/tests/test_decision_regions.py
=> Fix #93 - Expected shape of X_highlight

docs/make_api.py, docs/make_userguide.py, docs/mkdocs.yml, docs/sources/CHANGELOG.md, docs/sources/USER_GUIDE_INDEX.md, docs/sources/user_guide/plotting/checkerboard_plot.ipynb, mlxtend/__init__.py, mlxtend/feature_selection/sequential_feature_selector.py, mlxtend/plotting/__init__.py, mlxtend/plotting/checkerboard.py, mlxtend/plotting/tests/test_checkerboard.py
Adds a checkerboard plot to `plotting`
-
=> checkerboard_plot

.travis.yml, ci/.travis_install.sh, mlxtend/tf_classifier/tf_multilayerperceptron.py, mlxtend/tf_classifier/tf_softmax.py, mlxtend/tf_cluster/tf_kmeans.py, mlxtend/tf_regressor/tf_linear_regression.py
=> update tensorflow variable initialization to new api

mlxtend/classifier/multilayerperceptron.py, mlxtend/data/boston_housing.py, mlxtend/data/local_mnist.py, mlxtend/evaluate/tests/test_mcnemar_table.py, mlxtend/feature_extraction/tests/test_kernel_pca.py
just some style fixes to test out the "pep8speaks" bot
=> some style fixes

README.md, docs/sources/CHANGELOG.md, docs/sources/USER_GUIDE_INDEX.md, docs/sources/index.md, mlxtend/__init__.py
Setup for the next release version
=> prep for version 0.6.1

docs/sources/CHANGELOG.md, docs/sources/user_guide/data/autompg_data.ipynb, docs/sources/user_guide/data/wine_data.ipynb
Fixes typos in documentation for wine and autompg datasets
Fixes issue [#165](https://github.com/rasbt/mlxtend/issues/165)
=> Fixes typos in wine and autompg dataset documentation

docs/sources/CHANGELOG.md, mlxtend/math/counting.py, mlxtend/math/tests/test_counting.py
Made `math.num_combinations` and `math.num_permutations` numerically stable for large numbers of combinations and permutations
=> numerically stable counting

ci/.travis_install.sh, ci/.travis_test.sh, docs/sources/CHANGELOG.md, mlxtend/__init__.py, mlxtend/plotting/tests/test_checkerboard.py, mlxtend/plotting/tests/test_learning_curves.py
=> re-enable plotting tests

.travis.yml
... trying to see what's going on with travis-ci (#211)
=> push blank test to travis for testing

mlxtend/evaluate/lift_score.py
Fix Docstring in lift_score.py
https://github.com/rasbt/mlxtend/issues/219
<!-- Please provide a link to the respective issue on the [Issue Tracker](https://github.com/rasbt/mlxtend/issues) if one exists. E.g.,
Fixes #219
=> Fix lift score docstring False Positive

docs/sources/user_guide/evaluate/lift_score.ipynb
updates the lift doc string in the web docs according to #220 (and fixes #219)
=> update lift docstring in web docs

.conda/meta.yaml
Updated the conda recipe to the latest stable version.
Recipe automatically generated with `conda skeleton`, then manually tweaked to add missing
dependencies and repo links
The new `meta.yaml` file can just be uploaded to conda-forge to solve #218
=> Update conda recipe

docs/mkdocs.yml, docs/sources/USER_GUIDE_INDEX.md
Alphabetizes the user guide and API sections of the documentation. Hopefully this will make navigating the documentation easier. 
Fixes issue #231
=> Alphabetizes the user guide and API docs

docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
=> fix typo in sbs doc

docs/mkdocs.yml, docs/sources/CHANGELOG.md, docs/sources/USER_GUIDE_INDEX.md, docs/sources/user_guide/evaluate/permutation_test.ipynb, mlxtend/evaluate/__init__.py, mlxtend/evaluate/permutation.py, mlxtend/evaluate/tests/test_permutation.py
Permutation test for hypothesis testing (or A/B testing) to test if two samples come from the same distribution. Or in other words, a procedure to test the null hypothesis that that two groups are not significantly different (e.g., a treatment and a control group).
=> permutation test

docs/sources/user_guide/evaluate/permutation_test.ipynb, mlxtend/evaluate/permutation.py, mlxtend/evaluate/tests/test_permutation.py
Adds a `func` parameter to the permutation_test function to accept custom metrics.
=> add func parameter to permutation test

docs/sources/CHANGELOG.md, mlxtend/_base/_base_model.py, mlxtend/_base/_classifier.py, mlxtend/_base/_cluster.py, mlxtend/_base/_iterative_model.py, mlxtend/_base/_regressor.py, mlxtend/classifier/adaline.py, mlxtend/classifier/logistic_regression.py, mlxtend/classifier/multilayerperceptron.py, mlxtend/classifier/perceptron.py, mlxtend/classifier/softmax_regression.py, mlxtend/classifier/tests/test_adaline.py, mlxtend/classifier/tests/test_logistic_regression.py, mlxtend/classifier/tests/test_multilayerperceptron.py, mlxtend/classifier/tests/test_perceptron.py, mlxtend/classifier/tests/test_softmax_regression.py, mlxtend/cluster/kmeans.py, mlxtend/cluster/tests/test_kmeans.py, mlxtend/regressor/linear_regression.py, mlxtend/regressor/tests/test_linear_regression.py
Fix issues with `self._init_time` parameter in `_IterativeModel` subclasses.
=> Fix inittime

docs/sources/CHANGELOG.md, docs/sources/user_guide/classifier/EnsembleVoteClassifier.ipynb, docs/sources/user_guide/classifier/StackingCVClassifier.ipynb, docs/sources/user_guide/classifier/StackingClassifier.ipynb, docs/sources/user_guide/regressor/StackingCVRegressor.ipynb, docs/sources/user_guide/regressor/StackingRegressor.ipynb, mlxtend/classifier/ensemble_vote.py, mlxtend/classifier/stacking_classification.py, mlxtend/classifier/stacking_cv_classification.py, mlxtend/classifier/tests/test_ensemble_vote_classifier.py, mlxtend/classifier/tests/test_stacking_classifier.py, mlxtend/classifier/tests/test_stacking_cv_classifier.py, mlxtend/regressor/stacking_cv_regression.py, mlxtend/regressor/stacking_regression.py, mlxtend/regressor/tests/test_cv_stacking_regression.py, mlxtend/regressor/tests/test_stacking_regression.py
=> allow grid search for classifiers/regressors params in ensemble methods

docs/sources/CHANGELOG.md, mlxtend/evaluate/mcnemar.py
Improves the numerical stability of the exact McNemar test
=> stability improvements in exact mcnemar test

docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
Simply expands the author list in one of the references
=> Adds full Sequential Feature Selection reference

docs/sources/CHANGELOG.md, mlxtend/classifier/ensemble_vote.py, mlxtend/classifier/tests/test_ensemble_vote_classifier.py
=> Add unittests for testing the EnsembleVoteClassifier with class labels in string format

paper.md
👋 @rasbt - this should fix your submission over in https://github.com/openjournals/joss-reviews/issues/631
=> Fixing JOSS paper submission

docs/sources/CHANGELOG.md, mlxtend/classifier/stacking_classification.py, mlxtend/classifier/stacking_cv_classification.py, mlxtend/classifier/tests/test_stacking_classifier.py, mlxtend/classifier/tests/test_stacking_cv_classifier.py
Renames refit to use_clones in stacking classifiers
Fixes #367
=> Rename refit to use_clones in stacking classifiers

docs/sources/CHANGELOG.md, docs/sources/user_guide/feature_selection/ColumnSelector.ipynb, mlxtend/feature_selection/column_selector.py, mlxtend/feature_selection/tests/test_column_selector.py
This PR allows `ColumnSelector` to select columns on Pandas Dataframes.
=> ColumnSelector now works with pandas dataframes

README.md, docs/sources/CHANGELOG.md
Adds missing entry to changelog and fixes the citation reference
=> Documentation fixes

docs/sources/user_guide/feature_selection/ExhaustiveFeatureSelector.ipynb
=> Corrected typos in ExhaustiveFeatureSelection section of the userguide

mlxtend/classifier/tests/test_ensemble_vote_classifier.py
Just adds an additional unittest to the ensemble voting classifier to address a user question
=> add more ensemble vote unit tests

docs/sources/index.md
=> Update docs to point to JOSS paper

.travis.yml
See if travis can already support python 3.7. Check if coveralls is still working.
=> update travis to 3.7

docs/sources/CHANGELOG.md, docs/sources/user_guide/data/iris_data.ipynb, mlxtend/data/iris.py
Adding note about the difference in Iris dataset in UCI repo and R. 
Fixes #447
=> Iris dataset documentation

.appveyor.yml, .travis.yml, ci/.travis_install.sh, docs/sources/CHANGELOG.md, requirements.txt
=> Use native joblib instead of sklearn.externals.joblib

docs/sources/user_guide/frequent_patterns/apriori.ipynb
Documentation fix in apriori docs
Fixes #560
=> typo fix in apriori docs

.travis.yml
=> upd travis from python 3.6 to python 3.8

docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
=> Fix small typo in sffs doc

docs/sources/user_guide/feature_selection/ExhaustiveFeatureSelector.ipynb, docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
Adds an example to explain how one can calculate the adjusted R2 for exhaustive feature selection.
=> adjusted r2 example

docs/sources/CHANGELOG.md, docs/sources/user_guide/plotting/plot_confusion_matrix.ipynb, mlxtend/plotting/plot_confusion_matrix.py
=> Added options to input fig/ax in plot_confusion_matrix

docs/sources/user_guide/image/eyepad_align.ipynb
Fix typos in the documentation of the eyepad-align function.
=> fix eyepad doc

docs/mkdocs.yml, docs/sources/Code-of-Conduct.md
Adds a long overdue code of conduct.
=> Code of conduct

docs/sources/CHANGELOG.md, mlxtend/evaluate/bias_variance_decomp.py
=> Keras Sequential Model Support for Bias Variance Computation

docs/mkdocs.yml, docs/sources/CHANGELOG.md, docs/sources/USER_GUIDE_INDEX.md, docs/sources/user_guide/classifier/OneRClassifier.ipynb, mlxtend/classifier/__init__.py, mlxtend/classifier/oner.py, mlxtend/classifier/tests/test_oner.py
Adds a new `OneRClassifier` class for supervised learning / classification.
=> OneR classifier

docs/sources/CHANGELOG.md, docs/sources/user_guide/evaluate/accuracy_score.ipynb, mlxtend/evaluate/accuracy.py, mlxtend/evaluate/scoring.py, mlxtend/evaluate/tests/test_accuracy.py, mlxtend/evaluate/tests/test_scoring.py
Adds also scikit-learn-style balanced accuracy as another option.
=> add scikit-learn style balanced acc for comparison

README.md, docs/sources/index.md
updates links to point to Gh discussions
=> move to gh disucssions

docs/sources/CHANGELOG.md, mlxtend/evaluate/bootstrap_point632.py, mlxtend/evaluate/tests/test_bootstrap_point632.py
=> add fit_params to bootstrap

docs/sources/user_guide/frequent_patterns/fpgrowth.ipynb, mlxtend/frequent_patterns/fpgrowth.py
=> Fix whitespace issue in URL

mlxtend/plotting/heatmap.py
=> Missing `f` prefix on f-strings fix

docs/sources/CONTRIBUTING.md
Fixes some typos as discussed in #915
=> fix typos in contrib guide

docs/sources/user_guide/evaluate/mcnemar_table.ipynb
Thank you so much for this awesome library.
I noticed a typo and send this pull request.
None
=> Fix typo in documentation of mcnemar_table 

docs/sources/user_guide/classifier/EnsembleVoteClassifier.ipynb
=> Fix typo in EnsembleVoteClassifier.ipynb

docs/sources/user_guide/classifier/OneRClassifier.ipynb
Fixed a typo in the OneRClassifier.ipynb notebook.
=> Fix typo in OneRClassifier notebook

docs/sources/user_guide/frequent_patterns/fpgrowth.ipynb
Reviewed
Fixing minor typos in the markdown of notebooks for the FP-Growth webpage
=> Update minor typos in fpgrowth.ipynb

.github/workflows/publish.yaml, mlxtend/__init__.py
Adds a deployment workflow that automatically pushes the new version to PyPI when drafting a new release.
=> Add PyPI deploy workflow

docs/sources/CHANGELOG.md, mlxtend/__init__.py
Prep work for the v0.23.4 release
=> v0.23.4 release prep work
