rasbt/mlxtend

mlxtend/evaluate/learning_curves.py

Hi Sebastian,
I've started to use your extensions to assess my models before making submissions to Kaggle and found it quite useful so far. But in order to match Kaggle's evaluation methods for different competitions I added some functionality to the learning_curves function.
Basically, I added `predict_proba` to predict probabilities and `scoring` to select the metrics.
Regards.

Allow prediction of probabilities and selection of scoring method.

---

mlxtend/sklearn/ensemble.py

Relater to #6 
Add verbose in 4 levels:
```
`verbose=0` (default): prints nothing like right now
`verbose=1`: Print the number of the clf that is being fitted
`verbose=2`: Print info about the parameters of the clf that is being fitted
`verbose>2`:change the verbose of the  underlying clf to self.verbose - 2 
```
Example:
```
>>> import numpy as np
>>> from sklearn.linear_model import LogisticRegression
>>> from sklearn.naive_bayes import GaussianNB
>>> from sklearn.ensemble import RandomForestClassifier
>>> from mlxtend.sklearn import EnsembleClassifier
>>> clf1 = LogisticRegression(random_state=1)
>>> clf2 = RandomForestClassifier(random_state=1)
>>> clf3 = GaussianNB()
>>> X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
>>> y = np.array([1, 1, 1, 2, 2, 2])
>>> …
```

add verbose to EnsembleClassifier

---

docs/sources/user_guide/evaluate/plot_learning_curves.ipynb
docs/sources/user_guide/preprocessing/shuffle_arrays_unison.ipynb
mlxtend/preprocessing/shuffle.py

This small PR replaces the `random_state` parameter with `random_seed` in docstrings of `shuffle_arrays_unison`. Solves #81.

Replace random_state occurrences in shuffle_arrays_unison

---

mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py

Change max_score in line 243 to accommodate smaller negative values. For example, when using 'mean_squared_error', the call to get_scorer results in a make_scorer function with 'greater_is_better = False', such that values less than -1 can occur (the sign is flipped on the result of mse). Changed to float('-inf'), or could be -10**9, etc.

change max_score - line 243

---

docs/sources/CHANGELOG.md
mlxtend/classifier/stacking_cv_classification.py
mlxtend/classifier/tests/test_ensemble_vote_classifier.py
mlxtend/classifier/tests/test_stacking_classifier.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py
mlxtend/feature_selection/exhaustive_feature_selector.py
mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_column_selector.py
mlxtend/feature_selection/tests/test_exhaustive_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py
mlxtend/plotting/tests/test_learning_curves.py
mlxtend/preprocessing/tests/test_copy_transformer.py
mlxtend/preprocessing/tests/test_dense_transformer.py
mlxtend/regressor/tests/test_stacking_regression.py
mlxtend/text/names.py

Please make sure that these boxes are checked before submitting a new pull request -- thank you!
Uses the `model_selection` module that was added to scikit-learn 0.18 to avoid deprecation warning for scikit-learn 0.18 users. These modifications maintain backwards compatibility to 0.17.
Fixes #109
**Note:**  
**Due to the improved GitHub UI, the squashing of commits is no longer necessary. (Please don't squash commits since they help with keeping track of the changes during the discussion).**
For more information and instructions, please see http://rasbt.github.io/mlxtend/contributing/

compatibility layer for sklearn 0.18 model_selection

---

.github/PULL_REQUEST_TEMPLATE.md
mlxtend/evaluate/__init__.py
mlxtend/evaluate/decision_regions.py
mlxtend/evaluate/learning_curves.py
mlxtend/evaluate/plot_confusion_matrix.py
mlxtend/feature_selection/__init__.py
mlxtend/feature_selection/plot_sequential_feature_selection.py
mlxtend/feature_selection/sequential_feature_selector.py

Fixes #113
Added deprecation warnings so that plotting functions that have been moved from other sub packages into `mlxtend.plotting` can still be used as previously up to mlxtend 0.6

deprecation warning for plotting functions

---

docs/sources/user_guide/file_io/find_files.ipynb
mlxtend/file_io/find_files.py

Add missing whitespace to format the `find_files` docstring correctly.
Fixes #117

fix formatting in findfiles docstring

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py

Bugfix that changes the default argument for the `k_features` parameter in the `SequentialFeatureSelector` that was accidentally `'best'` instead of `1`.

fix default value for k_features in SFS

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/sequential_feature_selector.py

Cast selected feature subsets in the SequentialFeautureSubsets as sets to prevent the iterator from getting stuck if the k_idx are different permutations of the same combination
This branch was built in response to ordering issue found in [issue #132](https://github.com/rasbt/mlxtend/issues/132)

Sdq ordering

---

mlxtend/plotting/learning_curves.py

I found that picture in [user guide](http://rasbt.github.io/mlxtend/user_guide/plotting/plot_learning_curves/) with learning curve shows (i think) unexpected behaviour (higher misclassification error with larger training size).

Fix perfomance vs. training size plotting in plot_learning_curve

---

docs/sources/CHANGELOG.md
mlxtend/classifier/stacking_classification.py
mlxtend/classifier/tests/test_stacking_classifier.py
mlxtend/regressor/stacking_regression.py
mlxtend/regressor/tests/test_stacking_regression.py

Some sklearn models (RF, KNN, LinearRegression, MLP, ...) support fitting target (`y`) in a multivariate way or at least support multiple targets fitted simultaneously. Provided all underlying models support this, there is no reason for `StackingClassifier` and `StackingRegressor` not to.

StackingClassifier, StackingRegressor: allow multi-target y

---

docs/sources/CHANGELOG.md
mlxtend/plotting/decision_regions.py

- Adds a black `edgecolor` to plots via `plotting.plot_decision_regions` to make markers more distinguishable from the background in `matplotlib>=2.0`.

Matplotlib Edgecolor

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/exhaustive_feature_selector.py
mlxtend/feature_selection/sequential_feature_selector.py
requirements.txt

Use 1 process per feature for sequential feature selection and exhaustive feature selection
Fixes #191

Multiprocessing over features rather than CV folds in Sequential Feature Selection (addressing #191)

---

docs/sources/CHANGELOG.md
mlxtend/classifier/stacking_cv_classification.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py

Change the API of `StackingCVClassifier` in order to accept any kind of cross-validation technique. 
Related #202

Support for abstract cv method for StackingCVClassifier

---

docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
mlxtend/__init__.py

- New [mlxtend.plotting.ecdf](http://rasbt.github.io/mlxtend/user_guide/plotting/ecdf/) function for plotting empirical cumulative distribution functions ([#196](https://github.com/rasbt/mlxtend/pull/196)).
- New [`StackingCVRegressor`](http://rasbt.github.io/mlxtend/user_guide/regressor/StackingCVRegressor/) for stacking regressors with out-of-fold predictions to prevent overfitting ([#201](https://github.com/rasbt/mlxtend/pull/201)via [Eike Dehling](https://github.com/EikeDehling)).
- The TensorFlow estimator have been removed from mlxtend, since TensorFlow has now very convenient ways to build on estimators, which render those implementations obsolete.
- `plot_decision_regions` now supports plotting decision regions for more than 2 training features. …

0.7 release

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py

Fixes a bug where the `SequentialFeatureSelector` selected a feature subset larger than then specified via the `k_features` tuple max-value

fix bug where backw selection selected more features than specified

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py

Moving to nanmean allows the use of scorers that return nan without breaking existing functionality
Moved the means to `np.nanmean` to support scorers that may implement returning 

Move to nanmean instead of mean

---

docs/sources/user_guide/classifier/EnsembleVoteClassifier.ipynb
docs/sources/user_guide/classifier/StackingCVClassifier.ipynb
docs/sources/user_guide/classifier/StackingClassifier.ipynb

This PR adds examples showing how to use scikit-learn pipelines and the `ColumnSelector` to stack classifiers that were fit to different feature subsets.

Stacking classifiers from different feature subsets

---

README.md

Description
A small improvement to help out conda users to easily install mlxtend
Related issues or pull requests
Relates to #143, as mlxtend is now available through conda-forge

Add how-to install using conda

---

mlxtend/feature_selection/exhaustive_feature_selector.py

I modified the powerset function and calculation of number of possible combinations to reduce memory overhead by not longer storing all combinations as a list.
Fixes # https://github.com/rasbt/mlxtend/issues/194

Modified powerset function in EFS to reduce memory consumption

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py

`SequentialFeatureSelecor`'s `k_features` now accepts a string argument "best" or "parsimonious" for more "automated" feature selection. For instance, if "best" is provided, the feature selector will return the feature subset with the best cross-validation performance. If "parsimonious" is provided as an argument, the smallest feature subset that is within one standard error of the cross-validation performance will be selected. [#238](https://github.com/rasbt/mlxtend/pull/238)

best and parsimonious features for sfs

---

docs/sources/CHANGELOG.md
mlxtend/frequent_patterns/association_rules.py
mlxtend/frequent_patterns/tests/test_association_rules.py

- The `'support'` column returned by `frequent_patterns.association_rules` was renamed to `'antecedant support'`, and an additional `'consequent support'` column was added, to avoid ambiguity.

rename association rules columns

---

docs/sources/CHANGELOG.md
mlxtend/preprocessing/onehot.py
mlxtend/preprocessing/tests/test_onehot_transactions.py

The following
```python
from sklearn.base import clone
from mlxtend.preprocessing import OnehotTransactions
enc = OnehotTransactions()
clone(enc)
```
raises
```
TypeError: Cannot clone object '<mlxtend.preprocessing.onehot.OnehotTransactions object at 0x7f11d8ed7a90>' (type <class 'mlxtend.preprocessing.onehot.OnehotTransactions'>): it does not seem to be a scikit-learn estimator as it does not implement a 'get_params' methods.
```
because the class does not inherit from base classes in sklearn.
This is a fix

Inheritance in OnehotTransactions

---

docs/sources/CHANGELOG.md
mlxtend/classifier/ensemble_vote.py
mlxtend/classifier/stacking_classification.py
mlxtend/classifier/stacking_cv_classification.py
mlxtend/classifier/tests/test_ensemble_vote_classifier.py
mlxtend/classifier/tests/test_stacking_classifier.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py
mlxtend/regressor/stacking_cv_regression.py
mlxtend/regressor/stacking_regression.py
mlxtend/regressor/tests/test_cv_stacking_regression.py

Currently the parameters in `StackingClassifier`, `StackingCVClassifier`, `StackingRegressor`, `StackingCVRegressor`, and `EnsembleVoteClassifier` can't be tuned in `GridSearchCV`. This PR fixes that bug. 
Fixes #253

Add stacking param tuning

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/frequent_patterns/apriori.ipynb
mlxtend/frequent_patterns/apriori.py
mlxtend/frequent_patterns/tests/test_apriori.py

Adds a new `max_len` parameter for the frequent itemset generation via the `apriori` function to allow for early stopping.
Fixes #269

add max_len parameter to apriori

---

docs/sources/CHANGELOG.md
mlxtend/utils/counter.py
mlxtend/utils/tests/test_counter.py

Added a naming variable to utils.counter and chnaged time precision

Added optional name field to utils.counter

---

docs/mkdocs.yml
docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
docs/sources/user_guide/evaluate/bootstrap_point632_score.ipynb
mlxtend/evaluate/__init__.py
mlxtend/evaluate/bootstrap_point632.py
mlxtend/evaluate/mcnemar.py
mlxtend/evaluate/tests/test_bootstrap_point632.py

Implementation of the .632 boostrap

---

docs/sources/CHANGELOG.md
mlxtend/regressor/stacking_cv_regression.py
mlxtend/regressor/tests/test_cv_stacking_regression.py

modify fit and add an attribute self.train_meta_features_ for obtaining train meta-features,
and add a method predict_meta_features for obtaining test meta-features.
Sorry, I closed the previous PR https://github.com/rasbt/mlxtend/pull/294 by mistake, so I opened new one.
https://github.com/rasbt/mlxtend/issues/285
https://github.com/rasbt/mlxtend/issues/290
https://github.com/rasbt/mlxtend/pull/294

Refactor StackingCVRegressor so that users can obtain meta_features

---

docs/sources/CHANGELOG.md
mlxtend/evaluate/permutation.py

Library does not require `nose` to run.  I did a quick grep and a quick `from mlxtend import *` to confirm 
Fixes #302 
I did not add a test! We tested for "not requiring matplotlib" in `pymc3`, and it was a bit of a pain.  I can do the same here if you feel strongly.  Also, there are a bunch of flake8 failures not related to this change - it seems like this would be a bad PR adressing those.
- [~] Checked for style issues by running `flake8 ./mlxtend`

Nose is not required for running

---

docs/mkdocs.yml
docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
docs/sources/user_guide/evaluate/bootstrap.ipynb
docs/sources/user_guide/evaluate/cochrans_q.ipynb
mlxtend/evaluate/__init__.py
mlxtend/evaluate/cochrans_q.py
mlxtend/evaluate/tests/test_cochran_q.py

New function (`evaluate.cochrans_q`) for performing Cochran's Q test to compare the accuracy of multiple classifiers.

cochrans q test

---

docs/mkdocs.yml
docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
docs/sources/user_guide/evaluate/paired_ttest_resample.ipynb
mlxtend/__init__.py
mlxtend/evaluate/__init__.py
mlxtend/evaluate/tests/test_paired_ttest_resampled.py
mlxtend/evaluate/ttest.py

Implements the resampled pair t-test procedure
to compare the performance of two models
also called K-hold-out paired t-test).

resampled paired t-test

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/feature_selection/ColumnSelector.ipynb
mlxtend/feature_selection/column_selector.py
mlxtend/feature_selection/tests/test_column_selector.py

Adds a `drop_axis` attribute so that the column selector can be used in combination with e.g., count vectorizers which expect 1-dim arrays.

add drop_axis option to ColumnSelector

---

docs/sources/CHANGELOG.md
mlxtend/classifier/stacking_classification.py
mlxtend/classifier/stacking_cv_classification.py
mlxtend/classifier/tests/test_stacking_classifier.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py
mlxtend/externals/estimator_checks.py
mlxtend/regressor/stacking_cv_regression.py
mlxtend/regressor/stacking_regression.py
mlxtend/regressor/tests/test_stacking_cv_regression.py
mlxtend/regressor/tests/test_stacking_regression.py

Make sure that all stacking estimators raise `NonFittedError`s when an inference method is called prior to `fit`.
Fixes #289

raise notfittederror in stacking estimators

---

docs/sources/CHANGELOG.md
mlxtend/_base/_base_model.py
mlxtend/classifier/softmax_regression.py
mlxtend/classifier/tests/test_adaline.py
mlxtend/classifier/tests/test_ensemble_vote_classifier.py
mlxtend/classifier/tests/test_logistic_regression.py
mlxtend/classifier/tests/test_multilayerperceptron.py
mlxtend/classifier/tests/test_perceptron.py
mlxtend/classifier/tests/test_softmax_regression.py
mlxtend/classifier/tests/test_stacking_classifier.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py
mlxtend/cluster/tests/test_kmeans.py
mlxtend/externals/signature_py27.py
mlxtend/feature_selection/tests/test_exhaustive_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py
mlxtend/regressor/tests/test_linear_regression.py
mlxtend/regressor/tests/test_stacking_cv_regression.py
mlxtend/regressor/tests/test_stacking_regression.py

Adds `get_params` and `set_params` methods so that mlxtend estimators can be cloned via scikit-learn's clone function.
Fixes #372

Allow estimators to be cloned

---

mlxtend/feature_selection/sequential_feature_selector.py

I ran across a few lines that appear to be duplicates of previous lines in the `SequentialFeatureSelector.__init__` method. This PR simply removes the duplicates.

Removes a few duplicate lines from SequentialFeatureSelector __init__

---

docs/mkdocs.yml
docs/sources/CHANGELOG.md
docs/sources/user_guide/math/vectorspace_dimensionality.ipynb
docs/sources/user_guide/math/vectorspace_orthonormalization.ipynb
mlxtend/math/__init__.py
mlxtend/math/linalg.py
mlxtend/math/tests/test_linalg.py

Adds two new functions, `vectorspace_orthonormalization` and `vectorspace_dimensionality` were added to `mlxtend.math` to use the Gram-Schmidt process to convert an orthogonal vectorspace into orthonormal basis vectors and to compute the dimensionality of a vectorspace, respectively.
- -

gram schmidt process for orthonormal basis vectors and checking dimensionality

---

mlxtend/regressor/stacking_regression.py

bug fix when usin 'refit=False'

bug fix when usin 'refit=False'

---

mlxtend/regressor/stacking_cv_regression.py

bug fix when using refit=False

bug fix when using refit=False

---

mlxtend/frequent_patterns/tests/test_association_rules.py

Adds unit tests to check if frozensets don't cause problems in Python 2.7 if use_colnames=True in `apriori` function
#390

Unit tests to check if frozensets don't cause problems in Python 2.7

---

docs/sources/CHANGELOG.md
mlxtend/frequent_patterns/apriori.py
mlxtend/frequent_patterns/tests/test_apriori.py

Changes `apriori` to return itemsets as sets instead of lists.
Disscused in [issue 344](https://github.com/rasbt/mlxtend/issues/344)

Apriori use sets

---

docs/sources/user_guide/classifier/EnsembleVoteClassifier.ipynb

This extends the documentation explaining how the `voting='soft'` values are used and what it might mean if the SVM probabilities are estimated in a way that deviates from predicted class labels.

Adds an explanation about SVM and soft-voting behavior in the ensemble voting classifier

---

mlxtend/plotting/learning_curves.py

Fixes a broken link to the `plot_learning_curves` function in the documentation
Fixes #397

fix broken link to learning curves

---

docs/sources/user_guide/evaluate/feature_importance_permutation.ipynb
docs/sources/user_guide/preprocessing/minmax_scaling.ipynb
mlxtend/preprocessing/scaling.py

Fixes typo in minmax_scaling docstring mentioned in #355 and another grammar issue

Typo fixes

---

docs/sources/CHANGELOG.md
mlxtend/classifier/stacking_classification.py
mlxtend/classifier/tests/test_stacking_classifier.py

This PR adds support for sparse matrices in StackingClassifier when `use_features_in_secondary` in secondary is set to True. To do so, an extra branch in the `fit`, `predict` and `predict_proba` methods has been added to check if the input is a sparse matrix. In that case not `np.hstack` but `scipy.sparse.hstack` is used to merge the predictions of the meta classifiers and the input matrix.
This fixxes #408. It does not contain fixxes for e.g. StackingClassifierCV as mentioned in the discussion there.

Add support for sparse matrices in StackingClassifier

---

mlxtend/regressor/tests/test_stacking_regression.py

Adds a unit test to verify that the `StackingRegressor` supports scipy sparse matrices as input.
Fixes #411

Test sparse input for StackingRegressor

---

docs/sources/CHANGELOG.md
mlxtend/regressor/stacking_cv_regression.py
mlxtend/regressor/tests/test_stacking_cv_regression.py

add support for sparse matrices to StackingCVRegressor if use_features_in_secondary=True
Fixes #412

Add support for sparse matrices to StackingCVRegressor if use_features_in_secondary=True

---

docs/sources/CHANGELOG.md
mlxtend/classifier/stacking_cv_classification.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py

Allow `StackingCVClassifier` to work with sparse matrices when `use_features_in_secondary=True`
Fixes #413 
Fixes #408

Sparse support for StackingCVClassifier

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/regressor/StackingRegressor.ipynb
mlxtend/regressor/stacking_regression.py
mlxtend/regressor/tests/test_stacking_regression.py

Adding support for merging the meta features with the original input features in `StackingRegressor` (via `use_features_in_secondary`) like it is already supported in the other Stacking classes. 
Fixes #418

Option to pass orig features to meta regressor in stackingregressor

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/frequent_patterns/apriori.ipynb
mlxtend/frequent_patterns/apriori.py
mlxtend/frequent_patterns/tests/test_apriori.py

Now raises an error if the input to `mlxtend.frequent_patterns.apriori` is not 0, 1, True, or False, to avoid unintended behavior.
Fixes #407

raise error for unallowed values in DataFrame as input to apriori

---

docs/sources/CHANGELOG.md
mlxtend/_base/_classifier.py
mlxtend/_base/_regressor.py

Addresses numpy 0.15 deprecation warnings
- -

Addresses numpy 0.15 deprecation warnings

---

docs/sources/user_guide/evaluate/feature_importance_permutation.ipynb

On several occasions variable importance_vals was used instead of imp_vals.

Fixed variable names

---

docs/sources/user_guide/frequent_patterns/association_rules.ipynb

Fixes a typo in the Jupyter docs, where antecedAnt was used instead of antecedEnt based on an older mlxtend version.
#431

Fix antecedEnt typo in docs

---

docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb

Adds a documentation example for showing how to use pre-defined training/validation splits in the SequentialFeatureSelector
Fixes #436

Add PredefinedSplit example to SFS docs

---

docs/sources/CHANGELOG.md
mlxtend/classifier/ensemble_vote.py
mlxtend/classifier/stacking_classification.py
mlxtend/classifier/stacking_cv_classification.py
mlxtend/classifier/tests/test_ensemble_vote_classifier.py
mlxtend/classifier/tests/test_stacking_classifier.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py
mlxtend/regressor/stacking_cv_regression.py
mlxtend/regressor/stacking_regression.py
mlxtend/regressor/tests/test_stacking_cv_regression.py
mlxtend/regressor/tests/test_stacking_regression.py

Adds `sample_weight` option to the `fit` method of estimators.
Aims to cover the followings:
Fixes #438

Adds sample_weight option to estimators fit method

---

.travis.yml
ci/.travis_install.sh
docs/mkdocs.yml
docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
docs/sources/user_guide/evaluate/RandomHoldoutSplit.ipynb
mlxtend/evaluate/__init__.py
mlxtend/evaluate/holdout.py
mlxtend/evaluate/tests/test_holdout.py

Adds a `RandomHoldoutSplit` class to perform a train/valid split without rotation in `SequentialFeatureSelector`, scikit-learn `GridSearchCV` etc.

randomholdoutsplit

---

docs/mkdocs.yml
docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
docs/sources/user_guide/classifier/EnsembleVoteClassifier.ipynb
docs/sources/user_guide/classifier/StackingCVClassifier.ipynb
docs/sources/user_guide/classifier/StackingClassifier.ipynb
docs/sources/user_guide/evaluate/PredefinedHoldoutSplit.ipynb
docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
docs/sources/user_guide/regressor/StackingCVRegressor.ipynb
docs/sources/user_guide/regressor/StackingRegressor.ipynb
mlxtend/evaluate/__init__.py
mlxtend/evaluate/holdout.py
mlxtend/evaluate/tests/test_holdout.py

Adds a `PredefinedHoldoutSplit` class to perform a train/valid split, based on user-specified indices, without rotation in `SequentialFeatureSelector`, `GridSearchCV`, etc.

PredefinedHoldoutSplit

---

mlxtend/classifier/tests/test_ensemble_vote_classifier.py
mlxtend/classifier/tests/test_stacking_classifier.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py
mlxtend/evaluate/tests/test_bootstrap_point632.py
mlxtend/evaluate/tests/test_feature_importance.py
mlxtend/evaluate/tests/test_holdout.py
mlxtend/evaluate/tests/test_paired_ttest_5x2cv.py
mlxtend/evaluate/tests/test_paired_ttest_kfold.py
mlxtend/evaluate/tests/test_paired_ttest_resampled.py
mlxtend/feature_selection/tests/test_column_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py
mlxtend/plotting/tests/test_learning_curves.py
mlxtend/preprocessing/tests/test_copy_transformer.py
mlxtend/preprocessing/tests/test_dense_transformer.py
mlxtend/regressor/tests/test_stacking_cv_regression.py
mlxtend/regressor/tests/test_stacking_regression.py

Makes appropriate changes in unit tests to also support scikit-learn 0.20.

Support both scikit-learn 0.19 and 0.20 in unit tests

---

.travis.yml
ci/.travis_install.sh

In this particular Python 3.7 miniconda environment, pip has trouble installing coveralls
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"
Hence, for now, just use Python 3.6 for coveralls

try travis 3.7

---

docs/sources/user_guide/evaluate/lift_score.ipynb
mlxtend/evaluate/lift_score.py

I've noticed a minor error in the documentation for lift score calculation. The union in $support(true labels∪prediction)/N$ should actually be an intersect. This is correctly implemented in the code but also incorrect on the referenced Wikipedia article. I have changed it here and also modified a few other points in the doc:
- modified confusion matrix based lift formula. The numerator is now identical with model precision. Result remains identical.
- modified support based lift formula. This previously included N. However, with the way that support is implemented in the code, division by N is already part of the support calculation and should therefore not be listed separately in the equation.
- updated results so that number of decimal places shown matches up between the different …

minor correction and extension of doc on lift score calculation

---

.appveyor.yml
.travis.yml
README.md
docs/sources/CHANGELOG.md
docs/sources/index.md
docs/sources/user_guide/evaluate/bootstrap_point632_score.ipynb
mlxtend/evaluate/bootstrap_point632.py
mlxtend/evaluate/tests/test_bootstrap_point632.py

Adds the ".632+" bootstrap method to the `mlxtend.evaluate.bootstrap_point632_score` function.

.632plus bootstrap

---

docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
docs/sources/user_guide/evaluate/ftest.ipynb
mlxtend/evaluate/__init__.py
mlxtend/evaluate/f_test.py
mlxtend/evaluate/tests/test_f_test.py

Implements the F-test for comparing 2 or more classification models.

implementation of f-test

---

docs/sources/CHANGELOG.md
docs/sources/USER_GUIDE_INDEX.md
docs/sources/user_guide/evaluate/proportion_difference.ipynb

Add a difference of proportions test

proportion difference test

---

.travis.yml
docs/sources/user_guide/feature_extraction/PrincipalComponentAnalysis.ipynb

Language typo fixes in PCA docs

Language typo fixes in PCA docs

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/feature_extraction/PrincipalComponentAnalysis.ipynb
mlxtend/feature_extraction/principal_component_analysis.py
mlxtend/feature_extraction/tests/test_principal_component_analysis.py

Adds a `whitening` parameter to `PrincipalComponentAnalysis`, to optionally whiten the transformed data such that the features have unit variance.

Whitening parameter for PCA

---

docs/sources/CHANGELOG.md
mlxtend/feature_extraction/principal_component_analysis.py

The eigenvectors maybe have not been sorted in certain edge cases if solver was `'eigen'` in `PrincipalComponentAnalysis`.
Fixes #476

Sort eigvecs in PCA

---

.appveyor.yml
docs/sources/CHANGELOG.md
mlxtend/feature_extraction/linear_discriminant_analysis.py

- The eigenvectors maybe have not been sorted in certain edge cases in `LinearDiscriminantAnalysis`. ([#478](https://github.com/rasbt/mlxtend/pull/478))

Sort eigvecs in LDA

---

mlxtend/image/eyepad_align.py
mlxtend/image/tests/test_eyepad_align.py

Raises a meaningful error if `fit_dir` call in `EyePadAlign` can't find images files in the specified directory.

raise error if image directory is empty in eyepad align

---

docs/sources/user_guide/image/eyepad_align.ipynb
mlxtend/image/eyepad_align.py

Adds a pre-check for image dimensions and raises a warning if `fit_directory` and an image in the folder has dimensions that don't match the ones specified via the method arguments.
@vmirly

Adds a pre-check for image dimensions to EyepadAlign.fit_directory

---

docs/sources/CHANGELOG.md
mlxtend/frequent_patterns/apriori.py
mlxtend/frequent_patterns/tests/test_apriori.py

Raises a more informative error if a `SparseDataFrame` is passed to `apriori` and the dataframe has integer column names that don't start with `0` due to current limitations of the `SparseDataFrame` implementation in pandas.
Fixes #501

Raise apriori SparseDataFrame ValueError

---

docs/sources/CHANGELOG.md
mlxtend/plotting/plot_confusion_matrix.py

If show_normed is True, use the normed conf mat for *background* coloring instead of the absolute conf matrix, because *label* coloring (black/white) also follows normed conf matrix. This fixes unreadable labels that can occur with imbalanced datasets.
If arg `show_absolute=True` and `show_normed=True` the *background*-color is choosen by the absolute value, while the *label* color is chosen by the normed value. This can lead to unreadable labels for imbalanced dataset. 
Before / After:
n/a

Fix unreadable labels in plot_confusion_matrix in case of imbalanced data and show_normed=True

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/column_selector.py
mlxtend/feature_selection/tests/test_column_selector.py

Bug fix for selecting columns and add new features for the name of the columns of pandas data frame.

Applying to iloc of pandas data frame

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py

SequentialFeatureSelector now supports DataFrame as input for all operating modes (forward/backward/floating).
Fixes #505

Use values instead of DataFrame for all modes of SequentialFeatureSelector

---

docs/sources/CHANGELOG.md
mlxtend/regressor/stacking_cv_regression.py
mlxtend/regressor/tests/test_stacking_cv_regression.py

Use the sklearn born `cross_val_predict` to replace the explicit cv splitting loop. 
Add arguments `n_jobs` and `pre_dispatch` to be able to take advantage of parallel computation.

Introduce n_jobs to StackingCVRegressor

---

mlxtend/classifier/stacking_cv_classification.py
mlxtend/classifier/tests/test_stacking_cv_classifier.py

Updated `StackingCVClassifier` to use `safe_indexing` from `sklearn`.
Also did some refactoring: instead of iteratively concatenating the model predictions from each fold, I saved all the predictions in a list and concatenated them all at once. Not sure if the iterative concatenation was meant to save memory, but I thought it shouldn't really make a difference since the overhead of storing them all in a list should be quite small.
None! Was using this for Kaggle and found that it was breaking on fitting, so I added this fix!
Did some refactoring while fixing the code

Use of safe_indexing in StackingCVClassifier

---

docs/sources/CHANGELOG.md
mlxtend/evaluate/feature_importance.py
mlxtend/evaluate/tests/test_feature_importance.py

Bugfix, feature_importance_permutation can now accept functions as metric argument

---

docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
mlxtend/feature_selection/sequential_feature_selector.py

Some code rewrite that potentially addresses issues with GridSearch and nested parameter tuning if they existed.
Fixes #518
Fixes #511

Improved compatibility of seq feature selector and nested gridsearch

---

README.md

Fixes broken link in README.md
Fixes #530

Fix "contributing" link in readme

---

mlxtend/feature_selection/tests/test_sequential_feature_selector.py

Cleans up some unit tests
Fixes #536

Clean up compare_dict related unit tests

---

docs/sources/CHANGELOG.md
docs/sources/CONTRIBUTING.md
mlxtend/classifier/stacking_cv_classification.py
mlxtend/regressor/stacking_cv_regression.py

Changes to `StackingCVClassifier` and `StackingCVRegressor` such that first-level models are allowed to generate output of non-numeric type.
Fixes #562

Stacking dtype

---

docs/sources/CHANGELOG.md
mlxtend/feature_extraction/principal_component_analysis.py

In some cases, the number of eigenvalues when using the `svd` mode in the PCA could be smaller than the number of eigenvalues when using the eigensolver. This is fixed now.

Constant number of eigenvalues

---

docs/sources/user_guide/data/loadlocal_mnist.ipynb
mlxtend/__init__.py

Typo fix in MNIST dataset docs.
Fixes #571

fix mnist iris mixup

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/feature_selection/SequentialFeatureSelector.ipynb
mlxtend/feature_selection/sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector.py
mlxtend/feature_selection/tests/test_sequential_feature_selector_fixed_features.py

Adds a new `fixed_features` parameter to SFS for features to be forced to be included in the results.
#558

add fixed feature set support to SFS

---

docs/sources/user_guide/frequent_patterns/association_rules.ipynb

Fix inconsistency in docu (90%, but code says 0.7) and also typo in the same row. Minor PR. No unit test since only documentation was changed.

Fix inconsistency in association rules docu

---

docs/sources/CHANGELOG.md
mlxtend/data/tests/test_iris.py
mlxtend/feature_extraction/principal_component_analysis.py
mlxtend/feature_extraction/tests/test_principal_component_analysis.py

The `svd` mode of `mlxtend.feature_extraction.PrincipalComponentAnalysis` now also *n-1* degrees of freedom instead of *n* d.o.f. when computing the eigenvalues to match the behavior of `eigen`.

Change dof in svd-mode PCA to n-1

---

docs/sources/CHANGELOG.md
mlxtend/classifier/stacking_cv_classification.py

Disables input validation for `StackingCVClassifier` because it causes issues if pipelines are used as input.
Fixes #605

Disable input checking in StackingCVClassifier to support pipelines

---

mlxtend/evaluate/bootstrap.py

The pull request fixes a typo in the description of `num_rounds`.

Fix a typo in bootstrap

---

docs/sources/user_guide/evaluate/scoring.ipynb
mlxtend/evaluate/scoring.py
mlxtend/evaluate/tests/test_scoring.py

- Changed `'per-class accuracy'` and `'per-class error'` to `average 'per-class accuracy'` and `average 'per-class error'`, respectively, to improve clarity.
Fixes #616

rename "per-class accuracy" to "average per-class accuracy"

---

docs/sources/CHANGELOG.md
mlxtend/frequent_patterns/apriori.py
mlxtend/frequent_patterns/fpcommon.py
mlxtend/frequent_patterns/fpgrowth.py
mlxtend/frequent_patterns/fpmax.py
mlxtend/frequent_patterns/tests/test_fpbase.py

This PR improves performance of apriori for medium to large datasets, in particular with low_memory=True.  Situation is less clear for very small datasets.

Improve performance of apriori

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/frequent_patterns/apriori.ipynb
mlxtend/frequent_patterns/apriori.py
mlxtend/frequent_patterns/fpcommon.py
mlxtend/frequent_patterns/tests/test_fpbase.py

SparseDataFrame has been deprecated, pandas 0.24 recommands to create
standard DataFrames and store sparse Series as SparseArray.  This
allows to combine both dense and sparse columns.
Improve `valid_input_check` with sparse values; it previously uncompressed
the whole dataframe to check for invalid values, which defeats its purpose.
It now only checks existing values, which prevents memory error, and is
also much faster.
Update apriori.ipynb notebook to use the new pandas sparse DataFrame.

add support for newer pandas sparse dataframes in frequent_patterns

---

.appveyor.yml
.travis.yml
ci/.travis_install.sh

Fixes versions of dlib, imageio, scikit-image  for some tests in travis.

Add fixed dlib, imageio, scikit-image versions to travis

---

docs/sources/user_guide/data/loadlocal_mnist.ipynb

Adds a small modification that considers the different file naming scheme after unzipping on Windows.

Make loadlocal_mnist docs compatible with windows

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/data/loadlocal_mnist.ipynb
docs/sources/user_guide/evaluate/bootstrap_point632_score.ipynb
mlxtend/evaluate/bootstrap_point632.py
mlxtend/evaluate/tests/test_bootstrap_point632.py

Fixes an issue with using `meshgrid` in `no_information_rate` function used by the `bootstrap_point632_score` function for the .632+ estimate. 
#687

No info rate

---

docs/sources/CHANGELOG.md
mlxtend/text/names.py
mlxtend/text/tokenizer.py

Switched to using raw strings for regex in `mlxtend.text` to prevent deprecation warning in Python 3.8
Fixes #681

Use raw strings in regex

---

docs/sources/CHANGELOG.md
mlxtend/frequent_patterns/fpmax.py
mlxtend/frequent_patterns/tests/test_fpmax.py

Fix for bug 690, where fpmax returned incorrect support values

---

mlxtend/feature_selection/exhaustive_feature_selector.py

This is a faster and more idiomatic way of using `itertools.chain`. Instead of computing all the items in the iterable and storing them in memory, they are computed one-by-one and never stored as a huge list. This can save on both runtime and memory space.

Use chain.from_iterable in exhaustive_feature_selector.py

---

docs/sources/CHANGELOG.md
mlxtend/evaluate/bootstrap_point632.py
mlxtend/evaluate/tests/test_bootstrap_point632.py

Add ability to pass in `scoring_func` to `bootstrap_point632_score` function that depends on probability predictions rather then label predictions. This would for example allow `roc_auc_score` to be passed into the bootstrapping method.
Closes: #699

[WIP] Adding predict_proba ability to `bootstrap_632` functions

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/sequential_feature_selector.py

Implements slicing the features from the data before copying it to the subprocess.
Fixes #704
- [x ] Added a note about the modification or contribution to the `./docs/sources/CHANGELOG.md` file (if applicable)
- [ x] Ran `PYTHONPATH='.' pytest ./mlxtend -sv` and make sure that all unit tests pass (for small modifications, it might be sufficient to only run the specific test file, e.g., `PYTHONPATH='.' pytest ./mlxtend/classifier/tests/test_stacking_cv_classifier.py -sv`)
- [x ] Checked for style issues by running `flake8 ./mlxtend`

Forward slection reduce mem copy

---

mlxtend/evaluate/bias_variance_decomp.py

Removes a redundant line of code in the bias-variance decomposition function.
#707

Remove redundant code line

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/evaluate/permutation_test.ipynb
mlxtend/evaluate/permutation.py
mlxtend/evaluate/tests/test_permutation.py
mlxtend/feature_extraction/tests/test_principal_component_analysis.py

Permutation tests (`mlxtend.evaluate.permutation.py`) should return as p-value the proportion of permutations for which the calculated statistic is *at least as extreme* as the one observed in the experiment. (See in particular reference [3] of Wikipedia [p-value](https://en.wikipedia.org/wiki/P-value) page).
The current code only takes into account *more* extreme values.
In cases of approximation running a series of permutations but not all, it is also common to include the actual experiment as one additional permutation, avoiding the possible p-value of 0 and also closer to the exact p-value when the number of rounds is close to the number of possible combinations, as explained in detail in this [paper](https://pubmed.ncbi.nlm.nih.gov/21044043/):
> Phipson B, Smyth GK. Permutation …

Permutations

---

docs/sources/user_guide/frequent_patterns/fpmax.ipynb

Change 
"However, the runtime of Apriori can be quite small" 
to 
"However, the runtime of Apriori can be quite large"
"small" to "large" as I think that might be how it was meant to originally read.

Fix small typo in Fpmax user guide

---

mlxtend/feature_selection/sequential_feature_selector.py

Clarifies the use of `fit_params` in SFS docstring as discussed on the mailing list at https://groups.google.com/g/mlxtend/c/Xn3FWaVzLTc/m/qXPlq3GHCAAJ

Clarify fit_params docs for SFS

---

.appveyor.yml
.travis.yml
docs/sources/CHANGELOG.md
docs/sources/user_guide/evaluate/bias_variance_decomp.ipynb
mlxtend/evaluate/bias_variance_decomp.py
mlxtend/evaluate/tests/test_bias_variance_decomp.py

Improves the keras support in `bias_variance_decomp` and adds a `fit_params` parameter. Also provides documentation (Example 3).
Fixes #746

bias_variance_decomp fit_params and improved keras support

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/evaluate/bias_variance_decomp.ipynb
mlxtend/evaluate/bias_variance_decomp.py
mlxtend/evaluate/tests/test_bias_variance_decomp.py

Fixes a bug in `bias_variance_decomp` where when the `mse` loss was used, downcasting to integers caused imprecise results for small numbers. 
Fixes  #743

Fix integer bug in bias_variance_decomp

---

docs/sources/CHANGELOG.md
mlxtend/evaluate/mcnemar.py
mlxtend/evaluate/tests/test_mcnemar_table.py
mlxtend/evaluate/tests/test_mcnemar_tables.py

Fixing the table layout for McNemar's test and changed corresponding unit tests accordingly.
Fixes #664

fixed table layout for McNemar's test

---

mlxtend/evaluate/bootstrap_point632.py
mlxtend/evaluate/tests/test_bootstrap_point632.py

`evaluate.bootstrap_point632_score` can now handle Pandas' DataFrame/Series inputs without throwing errors.

Bootstrap pandas compatibility

---

mlxtend/feature_selection/sequential_feature_selector.py

There is a small typo in mlxtend/feature_selection/sequential_feature_selector.py.
Should read `validation` rather than `validtion`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, validtion -> validation

---

mlxtend/plotting/tests/test_pca_corr_graph.py

fix pca import problem

---

docs/sources/user_guide/evaluate/bias_variance_decomp.ipynb
mlxtend/evaluate/bias_variance_decomp.py

Clarifies how bootstrapping is used in the `bias_variance_decomposition` (#786)

Clarifies how bootstrapping is used in the `bias_variance_decomposition`

---

docs/sources/CHANGELOG.md
mlxtend/plotting/decision_regions.py

Removes deprecates `res` (resolution) parameter from `plot_decision_regions`

Remove depr. res from plot_decision_regions

---

mlxtend/evaluate/bias_variance_decomp.py
mlxtend/evaluate/tests/test_bias_variance_decomp.py

Raises a more descriptive `ValueError` if user uses a pandas DataFrame in the `bias_variance_decomp` func where it is currently not explicitly supported yet

Notify users about about pandas dataframe use in bias_variance_decomp

---

docs/sources/CHANGELOG.md
mlxtend/frequent_patterns/association_rules.py
mlxtend/frequent_patterns/tests/test_association_rules.py

The `frequent_patterns.association_rules` now raises a `ValueError` if an empty frequent itemset DataFrame is passed. 
Fixes #496

Raise error on empty frequent itemset to association_rules

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/evaluate/bootstrap_point632_score.ipynb
mlxtend/evaluate/bootstrap_point632.py
mlxtend/evaluate/tests/test_bootstrap_point632.py

The .632 and .632+ bootstrap method implemented in the `mlxtend.evaluate.bootstrap_point632_score` function now use the whole training set for the resubstitution weighting term instead of the internal training set that is a new bootstrap sample in each round
#842

use whole training set in .632 and .632+ bootstrap

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/evaluate/mcnemar.ipynb
docs/sources/user_guide/evaluate/mcnemar_table.ipynb
docs/sources/user_guide/evaluate/mcnemar_tables.ipynb

This PR only fix some typos in McNemar guides where `contingency` was written `contigency`.

Contingency typo fix

---

mlxtend/frequent_patterns/fpcommon.py

Add warning about not bool type. This PR addresses issue #620.

Fixes #620 Add a warning about non Boolean inputs

---

mlxtend/evaluate/mcnemar.py

Fix typo in the following variable names
https://rasbt.github.io/mlxtend/user_guide/evaluate/mcnemar_tables/#api
>y_mod0 = np.array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0])
>y_mod0 = np.array([0, 0, 1, 1, 0, 1, 1, 0, 0, 0])
>y_mod0 = np.array([0, 1, 1, 1, 0, 1, 0, 0, 0, 0])
None

Fix typo in docstring of mcnamer_tables to increment numbers

---

mlxtend/evaluate/mcnemar.py
mlxtend/evaluate/tests/test_mcnemar_test.py

`mlxtend.evaluate.mcnemar` returns `None` as `chi2` when `exact=True`.
Fixes #989

mcnemar(tb, exact=True) returns None as chi2

---

docs/sources/CHANGELOG.md
mlxtend/__init__.py

This PR fixes issue #971 
```
seed = 0
X = np.random.rand(10000, 10) # 10k samples, with 10 features
y = np.random.choice([0, 1], size=10000)
lst = []
for i in range(5):
tic = time.time()
efs = EFS(RandomForestClassifier()).fit(X, y) # EFS: ExhaustiveFeatureSelector
toc = time.time()
lst.append(toc - tic)
np.mean(lst)
```
* branch `main`: 103 sec
* this branch: 93 sec

Fixed #971 turned off joblib when `n_jobs == 1`

---

docs/sources/CHANGELOG.md
mlxtend/classifier/ensemble_vote.py

What was done:
* Fixes #941 (Disable unnecessary warning in EnsembleVoteClassifier)
* Added it to changlog
* #980 'Enhancement: Zhangs metric' was placed in the wrong section in the change-log (was put under new features section of version **v0.20.0**, I moved it in to the right section (under new features section of **v0.21.0**)

Removed unnecessary warnings as described in #941

---

docs/sources/CHANGELOG.md
mlxtend/frequent_patterns/fpmax.py

While the current functionality supports sparse matrices on an API level, it calls `pd.DataFrame.values` in order to get the number of rows in the DataFrame. Unfortunately, `.values` forces the entire DataFrame to be converted into a non-sparse 2D numpy array. So using sparse matrices to fix an OOM doesn't actually make the OOM go away. 
This fix is semantically identical, in Pandas terms, except that it doesn't materialize a dense array just to find it's length.
N/A
* NOTE: 5 tests don't pass, but that's consistent with the state prior to this change.

Fix fpmax for sparse matrices

---

docs/sources/CHANGELOG.md
docs/sources/user_guide/frequent_patterns/hmine.ipynb
mlxtend/frequent_patterns/__init__.py
mlxtend/frequent_patterns/hmine.py
mlxtend/frequent_patterns/tests/test_hmine.py

New feature.
In order to enrich the library and to compare the speed and memory costs of certain algorithms, I added the hmine algorithm to the library.
None

Added Hmine algorithm

---

.github/workflows/python-package-conda.yml
mlxtend/frequent_patterns/tests/test_fpbase.py
mlxtend/frequent_patterns/tests/test_hmine.py

Fix.
Test codes with errors (or usage may have changed) have been fixed.
None

Fixed incorrect test codes.

---

docs/sources/CHANGELOG.md
mlxtend/regressor/tests/test_stacking_cv_regression.py
mlxtend/regressor/tests/test_stacking_regression.py

The new version of sklearn's LinearRegression does not allow `normalize` paramter which is depreciated in the newer versions. So I fixed that.
`Fixes Arg normalize to sklearn.linear_model.LinearRegression has been removed in version 1.2 #1035`

Sklearn normalize depreciation fix

---

mlxtend/evaluate/bias_variance_decomp.py
mlxtend/evaluate/holdout.py

As in the issue `Leftover use of np.int and np.bool #1034` I have replaced the `np.int` and `np.bool`  with `np.int_` and `np.bool_` in the `bias_variance_decomp.py` and `holdout.py` files.
Fixes Leftover use of np.int and np.bool #1034

Replaced np.int and np.bool

---

mlxtend/feature_selection/tests/test_exhaustive_feature_selector.py

I have fixed the one error in `test_exhaustive_feature_selector.py` regarding sklearn depreciation in version 1.2
Fixes one of the issue of #889

Fixed load_boston test_exhaustive_feature_selector

---

docs/mdx_math_setup.py
mlxtend/frequent_patterns/fpcommon.py

updated dependency on distutils for python 3.12 and above

---

pyproject.toml

Tests should be included in the source distribution but there is no reason to include them in the built wheel.
Disable implicit packages (directories without an `__init__.py` file) altogether by setting the following in `pyproject.toml`:
```toml
[tool.setuptools.packages.find]
include = ["mlxtend", "mlxtend.*"]
namespaces = false
```
I assume the files in `mlxtend/data/data` are still needed so I've modified the package data to include files in that directory.
Build log extract from master:
```sh
$ git clean -fdx && python -m build --wheel --no-isolation
Removing build/
Removing dist/
Removing mlxtend.egg-info/
* Getting build dependencies for wheel...
validate_pyproject.api.load_builtin_plugin defines `tool.distutils` schema
validate_pyproject.api.load_builtin_plugin defines …
```

Don't include tests in built wheel

---

mlxtend/evaluate/tests/test_bias_variance_decomp.py

Refactors two tests in `evaluate/tests/test_bias_variance_decomp.py` (change `base_estimator` to `estimator`). This fixes two failing unit tests.
None.

Refactor bias_variance_decomposition test.

---

docs/sources/CHANGELOG.md
mlxtend/feature_extraction/principal_component_analysis.py

Use scipy's decompositions in PCA.
Fixes https://github.com/rasbt/mlxtend/issues/1078

Use scipy's decompositions in PCA.

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/sequential_feature_selector.py

Update numpy negative infinity constant for version compatibility for the sequential feature selector (SFS)
- Add version check to handle different numpy versions
- Use `np.NINF` for numpy <2.0 and `-np.inf` for numpy >=2.0
- Replace direct `np.NINF` usage with version-aware variable
- Maintain backward compatibility while supporting newer numpy versions
This change ensures the code works correctly across different numpy versions
while maintaining the same functionality.
fixes #1100 related issue
#1104 similar but incomplete PR

SFS finalize_fit() support for numpy >= 2.0

---

docs/sources/CHANGELOG.md
mlxtend/feature_selection/utilities.py

Refactor `_calc_score'` to accommodate scikit-learn versioning
- Updated `_calc_score` to dynamically select the appropriate parameter name (`'fit_params'` or `'params'`) for `cross_val_score` based on the *scikit-learn* version.
- Ensures compatibility with both older versions (below 1.4) and newer versions (1.4 and above) of *scikit-learn*
fixes #1082

Fixed `_calc_score` for *scikit-learn* version compatibility

---

docs/sources/CHANGELOG.md
mlxtend/evaluate/time_series.py

* added title to legend
* adjusted xticklabels for Sample Index not to intersect with each other anymore
* added legend for groups (setting it as xtick with xticklabels would be quite time-intense because the scale on the x-axis changes depending depending on the `window_type` (`'expanding'` or `'rolling'`).
fixes #1094

Improved `plot_splits` for time series splits

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/publish.yaml

* updates the GitHub Actions `publish` workflow to reference the latest versions of actions used in the `steps` section under `uses` to improve performance, security, and compatibility with the latest GitHub Actions features.
* fixes typo in PR template
--

Updated `publish` CI/CD workflow
